library(tidyverse)

NSDUH_2002_Edit <- NSDUH_2002_Tab_Edit %>% select(FILEDATE, CIGEVER, CIGTRY, CIGREC, CIG30AV, CIGAGE, ALCEVER, ALCTRY, ALCREC, ALDAYPYR, ALCDAYS, ALCUS30D=NODR30A, 
                                                  MJEVER, MJAGE, MJREC, MJYRTOT, MJDAY30A, COCEVER, COCAGE, COCREC, COCYRTOT, COCUS30A, HEREVER, HERAGE, HERREC, 
                                                  HERYRTOT, HER30USE, HYDCPDAPYU=HYDROCOD, MTDNPDAPYU=METHDON, MORPPDAPYU=MORPHINE, OXCNANYYR=OXYCONTN, 
                                                  PNRNMLIF=ANLEVER, PNRNMAGE=ANALAGE, PNRNMREC=ANALREC, TRBENZAPYU=TRNEVER, TRQNMAGE=TRANAGE, AMMEPDPYMU=METHDES, 
                                                  METHPDAPYU=RITMPHEN, STMNMLIF=STMEVER, STMNMAGE=STIMAGE, IRMETHAMYFQ=STMYRTOT, METHAMAGE=METHAGE, METHAMYFQ=MTDAYPYR, 
                                                  METHDYPMO=MTDAYPMO, SEDNMLIF=SEDEVER, SEDNMAGE=SEDAGE, SEDNMREC=SEDREC, CIGAFU, DCIGAFU, ALCAFU, MJAFU, MRJYDAYS, 
                                                  COCYDAYS, METHNDAYYR=MTHYDAYS, ALCYDAYS, HALLNDAYPM=HALMDAYS, CIGMDAYS, DIFGETMRJ=RSKDIFMJ, DIFGETCOC=RKDIFCOC, 
                                                  DIFGETCRK=RKDIFCRK, DIFGETHER=RKDIFHER, APPDRGMON=RSKSELL, RSKYFQDGR=RKFQDNGR, RSKYFQTES=RKFQRSKY, RKFQPBLT, 
                                                  RKFQDBLT, DIFOBTMRJ=RDIFMJ, DIFOBTCOC=RDIFCOC, DIFOBTCRK=RDIFCRK, DIFOBTHER=RDIFHER, APPDRGMON2=APPSELDG, 
                                                  DEPNDALC, DEPNDPYPNR=DEPNDANL, DEPNDCOC, DEPNDHER, DEPNDMRJ, DEPNDPYILL=DEPNDILL, DEPNDPYIEM=DEPNDIEM, 
                                                  DPPYILLALC=DPILLALC, DPPYILANAL=DPILANAL, BOOKED, NOBOOKY2, PROBATON, DRVINALCO2=DRIVALC2, DRVINDRG=DRIVDRG2, 
                                                  DRVINALDRG=DRIVALD2, TXEVRRCVD=TXEVER, TXLTYDAYS2=TXLTYDU2, PREGNANT, NMERTMT2, INHOSPYR, DOMOSTYR, 
                                                  AUOPTYR, AURXYR, AMHINP2, RCVMHOSPTX=MHOSPTRT, RCVMHNSPTX=MHNSPTRT, RCVSPTXNMH=NMHSPTRT, RCVMHASPTX=MHASPTRT, 
                                                  SNYSELL, SNYSTOLE, SNYATTAK, SNRLGSVC, SNRLGIMP, SNRLDCSN, YEATNDYR, YEHMSLYR, YESCHFLT, YETCGJOB, YELSTGRD, 
                                                  YEPCHKHW, YEPCHORE, YEPLMTTV, YEPLMTSN, YEPGDJOB, YEPPROUD, YEYHGUN, ANYEDUC3, YHLTMDE=MDEDP2WK, K6SCMON=SMI_SUM, 
                                                  SPDYR=SMI, SMISUDPY=SMIADPAB, ANYSMH2=ANYSMH, SMHSUI2=REASSUIC, IMOTHER, IFATHER, NRCH17_2, GOVTPROG, INCOME, AGE2, 
                                                  NOMARR2, SERVICE, HEALTH, IRSEX, CATAGE, SEXAGE, NEWRACE2, EDUHIGHCAT=EDUCCAT2, PDEN10=PDEN90, COUTYP4=COUTYP2)

write.csv(NSDUH_2002_Edit, '/home/kylier/Documents/UNH/803/NSDUH_2002_Edit.csv')

  